<?php

namespace ContainerZgStx5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\VideoRepository' shared autowired service.
     *
     * @return \App\Repository\VideoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\VideoRepository'] = new \App\Repository\VideoRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
