<?php

namespace ContainerWccxjHc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_TranslationDebugService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'console.command.translation_debug' shared service.
     *
     * @return \Symfony\Bundle\FrameworkBundle\Command\TranslationDebugCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['console.command.translation_debug'] = $instance = new \Symfony\Bundle\FrameworkBundle\Command\TranslationDebugCommand(($container->services['translator'] ?? $container->getTranslatorService()), ($container->privates['translation.reader'] ?? $container->load('getTranslation_ReaderService')), ($container->privates['translation.extractor'] ?? $container->load('getTranslation_ExtractorService')), 'E:\\Video-Sharing-Platform/translations', 'E:\\Video-Sharing-Platform/templates', [0 => 'E:\\Video-Sharing-Platform\\vendor\\symfony\\validator/Resources/translations', 1 => 'E:\\Video-Sharing-Platform\\vendor\\symfony\\form/Resources/translations', 2 => 'E:\\Video-Sharing-Platform\\vendor\\symfony\\security-core/Resources/translations'], [0 => 'E:\\Video-Sharing-Platform\\vendor\\symfony\\twig-bridge/Resources/views/Email', 1 => 'E:\\Video-Sharing-Platform\\vendor\\symfony\\twig-bridge/Resources/views/Form', 2 => 'E:\\Video-Sharing-Platform\\vendor\\symfony\\framework-bundle\\Command\\TranslationDebugCommand.php', 3 => 'E:\\Video-Sharing-Platform\\vendor\\symfony\\form\\Extension\\Core\\Type\\FileType.php', 4 => 'E:\\Video-Sharing-Platform\\vendor\\symfony\\form\\Extension\\Core\\Type\\ColorType.php', 5 => 'E:\\Video-Sharing-Platform\\vendor\\symfony\\form\\Extension\\Core\\Type\\TransformationFailureExtension.php', 6 => 'E:\\Video-Sharing-Platform\\vendor\\symfony\\form\\Extension\\Validator\\Type\\UploadValidatorExtension.php', 7 => 'E:\\Video-Sharing-Platform\\vendor\\symfony\\form\\Extension\\Csrf\\Type\\FormTypeCsrfExtension.php', 8 => 'E:\\Video-Sharing-Platform\\vendor\\symfony\\validator\\ValidatorBuilder.php', 9 => 'E:\\Video-Sharing-Platform\\vendor\\symfony\\framework-bundle\\CacheWarmer\\TranslationsCacheWarmer.php', 10 => 'E:\\Video-Sharing-Platform\\vendor\\symfony\\translation\\DataCollector\\TranslationDataCollector.php', 11 => 'E:\\Video-Sharing-Platform\\vendor\\symfony\\twig-bridge\\Extension\\TranslationExtension.php']);

        $instance->setName('debug:translation');

        return $instance;
    }
}
