<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOHMHISW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOHMHISW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOHMHISW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOHMHISW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOHMHISW\App_KernelDevDebugContainer([
    'container.build_hash' => 'OHMHISW',
    'container.build_id' => '916324cc',
    'container.build_time' => 1602437604,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOHMHISW');
