<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxATsld\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxATsld/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYxATsld.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYxATsld\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYxATsld\App_KernelDevDebugContainer([
    'container.build_hash' => 'YxATsld',
    'container.build_id' => '0b24c046',
    'container.build_time' => 1602534474,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxATsld');
