<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJcoRHpA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJcoRHpA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJcoRHpA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJcoRHpA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJcoRHpA\App_KernelDevDebugContainer([
    'container.build_hash' => 'JcoRHpA',
    'container.build_id' => 'a6b0ac5b',
    'container.build_time' => 1602938836,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJcoRHpA');
